on:
  push:
  workflow_dispatch:

name: Update README

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update README source quotes
        run: |
          repo_url="https://github.com/Siphalor/function-pointer-madness"
          repo_url=$(sed 's/\//\\\//g' <<<"$repo_url")
          for f in $(grep -Po "\|\s+(.*blob/\w+)?/\K[^#]+" README.md)
          do
          	commit=$(git log -n 1 --pretty=format:%H -- $f)
          	f_url=$(sed 's/\//\\\//g' <<<"$f")
          	sed -i "s/| \([^|]*blob\/[a-zA-Z0-9]\+\)\?\/$f_url/| $repo_url\/blob\/$commit\/$f_url/" README.md
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README source quotes
          file_pattern: README.md
